### ISSUE TITLE
Metrics Server (Dashboard) #TODO

### ISSUE THREAD

**Issue by r120a** [HeliumDIY/helium_ansible#13]
- [ ] create Ansible role for a metrics server (prometheus, loki, prompushgateway, grafana)
- [ ] create shell script with functions to query api values and submit them to the Prometheus Push Gateway
- [ ] Create ansible tasks for the shell script with variables for hotspot addresses or account addresses to extract data for
